spring:
  application:
    name: cloud-gateway
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: uaa
            client-id: webapp
            authorization-grant-type: implicit
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          uaa:
            authorization-uri: http://localhost:${server.port}/uaa/oauth/authorize
            token-uri: http://localhost::${server.port}/uaa/oauth/token
            user-info-uri: http://localhost:${server.port}/uaa/user # user user info instead token info
  cloud:
    gateway:
      routes:
        - id: uaa
          uri: lb://auth-service
          predicates:
            - Path=/uaa/**
          filters:
            - StripPrefix=0
            - RewritePath=/uaa/(?<segment>.*), /$\{segment}
        - id: uaa
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=0
            - RewritePath=/account/(?<segment>.*), /$\{segment}

server:
  port: 8099


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

logging:
  level:
    org.springframework.cloud.gateway: trace